apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: monitoring
  namespace: monitoring
spec:
  version: 7.14.0
  nodeSets:
  - name: es
    count: 3
    config:
      node.store.allow_mmap: false
